### ISSUE TITLE
Bidirectional connections displayed unclearly.

### ISSUE THREAD

**Issue by CreoOne** [XXIIVV/Riven#12]
By specification, system that im trying to build using Riven requires p2p connection between nodes that expects every node to be server and client. Currently its possible for Riven to make such connections but they are not drawn clearly.

**Comment by neauoire** [comment]
You're talking about `.bind()` right? Can you give me a screen? They display correctly for me on chrome.

**Comment by CreoOne** [comment]
Sorry, it came from my misunderstanding of `.bind()`. It's all working.
