### ISSUE TITLE
Examples work in rawgit, please link!

### ISSUE THREAD

**Issue by brody2consult** [XXIIVV/Riven#2]
- <https://rawgit.com/XXIIVV/Riven/master/example.conditional.html>
- <https://rawgit.com/XXIIVV/Riven/master/example.math.html>

**Comment by neauoire** [comment]
What is rawgit?

**Comment by brody2consult** [comment]
> What is rawgit?

From first result of <https://www.google.com/search?q=rawgit>:
> RawGit serves raw files directly from GitHub with proper Content-Type headers.

Does this make sense? Do you have any other questions?

**Comment by neauoire** [comment]
It does but what do you mean by **please link**?

**Comment by neauoire** [comment]
From the README?

**Comment by brody2consult** [comment]
> From the README?

I would recommend it.

**Comment by neauoire** [comment]
ah! Absolutely :)
We're working on a couple of new examples, when they're done I will add them in the README.
Thanks!
