### ISSUE TITLE
Riven with JSX-enabled view (idea)

### ISSUE THREAD

**Issue by brody2consult** [XXIIVV/Riven#3]
Would be kinda like CycleJS, Hyperapp, React with Redux, etc. but cooler!

**Comment by neauoire** [comment]
What is JSX?

**Comment by sepiropht** [comment]
An html like syntax but in js. It is very popular with the react  framework from facebook

**Comment by neauoire** [comment]
Ah! Thank you :)
The nodes don't really have any specified language. It could be used to output JSX probably as is!
