### ISSUE TITLE
Ø Selector

### ISSUE THREAD

**Issue by lech** [XXIIVV/Riven#4]
On Windows, there's no easy way to produce "Ø" with ```"alt+shift+O"```, instead it's ```Alt +0216``` (on the number pad). This is also providing that the keyboard you're using makes this easy if you don't have a number pad. I don't know how this affects other distributions off the top of my head but suspect it might.

As a solution/work-around, renaming all instances of ```"Ø"``` with ```"rvn"``` in ```riven.js``` and any documents calling it works just as well. It may just be me, but using special characters for selectors or variable names is slightly annoying, otherwise this is pretty solid. 👍

**Comment by neauoire** [comment]
Ah! Well, I think the best would be to wrap the method into something else.
Try `function R(x){ return Ø(x); }`
