### ISSUE TITLE
Publishing a NPM package for Riven

### ISSUE THREAD

**Issue by swwwnsn** [XXIIVV/Riven#5]
This would make easier to work with Riven in environments like Webpack or even Node.

**Comment by neauoire** [comment]
That's a good idea, I've never done this before tho.

**Comment by swwwnsn** [comment]
https://github.com/1101computer/neo-riven Just did it for fun ;)

**Comment by neauoire** [comment]
Nice :) I'd love to see what you use Riven for.
Here are some of my riven maps.
http://grimgrains.com/riven.html
http://wiki.xxiivv.com/riven.html
