### ISSUE TITLE
Graph Visualisation changed for worse.

### ISSUE THREAD

**Issue by Izhaki** [XXIIVV/Riven#7]
So I was given a presentation on Redux, with a pivotal slide dealing with the differences between Redux and streams, or request/response vs fire/forget respectively - which are the two fundamental paradigms that constitute the axes of a Riven node.

And I thought "What a better way to demonstrate how polar these two are than showing the [web example graph from Riven](https://wiki.xxiivv.com/riven.html#home)", but to my surprise the graph has changed and is now WELL less clear than what it was a month ago.

Also, you can't scroll horizontally, which means that with my laptop you can't show the lot.

And there's no way to see the old graph.

Is this WIP? The old graph was way better! The old graph was very much like [this](https://www.youtube.com/watch?v=LqOJq0HeZMc), whereas the new one look more like [that](https://www.youtube.com/watch?v=kvz_gW5C2cY).

**Comment by neauoire** [comment]
I'm sorry, I've been doing some changes for my personal use.
I will try to improve the look of the viewer.
It's very much a work in progress, and I'm still trying to find the paradigms that work.
My site's graph is in flux [riven.js](http://wiki.xxiivv.com/riven.html) as I try to find better paradigms to accomplish what I'm trying to do, I will try to improve the look of things in a bit. 

I'm trying, at the moment, to add a flow for meshes that allows inward port connections, more on this shortly. I've also added a `init` flow, which sets the stage, and splits the queries from the initial db pull.
